// Generated by CoffeeScript 1.3.3
(function() {
  var Element;

  Element = (function() {

    function Element(value, browser) {
      if (value == null) {
        throw new Error("no value passed to element constructor");
      }
      if (browser == null) {
        throw new Error("no browser passed to element constructor");
      }
      this.value = value;
      this.browser = browser;
    }

    Element.prototype.toString = function() {
      return String(this.value);
    };

    Element.prototype.sendKeys = function(keys, cb) {
      return this.browser.type(this.value, keys, cb);
    };

    Element.prototype.click = function(cb) {
      return this.browser.clickElement(this.value, cb);
    };

    Element.prototype.text = function(cb) {
      return this.browser.text(this.value, cb);
    };

    Element.prototype.textPresent = function(searchText, cb) {
      return this.browser.textPresent(searchText, this.value, cb);
    };

    Element.prototype.getAttribute = function(name, cb) {
      return this.browser.getAttribute(this.value, name, cb);
    };

    Element.prototype.getValue = function(cb) {
      return this.browser.getValue(this.value, cb);
    };

    Element.prototype.getComputedCSS = function(styleName, cb) {
      return this.browser.getComputedCSS(this.value, styleName, cb);
    };

    Element.prototype.clear = function(cb) {
      return this.browser.clear(this.value, cb);
    };

    return Element;

  })();

  exports.Element = Element;

}).call(this);
