// Generated by CoffeeScript 1.3.3
(function() {
  var EventEmitter, SPECIAL_KEYS, Webdriver, k, protocol, v, wrap,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    __slice = [].slice;

  EventEmitter = require("events").EventEmitter;

  protocol = require("./protocol");

  SPECIAL_KEYS = require("./special-keys");

  Webdriver = (function(_super) {

    __extends(Webdriver, _super);

    function Webdriver() {
      this.browser = null;
    }

    return Webdriver;

  })(EventEmitter);

  wrap = function(f) {
    return function() {
      var args;
      args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
      return f.apply(this, args);
    };
  };

  for (k in protocol) {
    v = protocol[k];
    if (typeof v === "function") {
      Webdriver.prototype[k] = wrap(v);
    }
  }

  exports.remote = function() {
    return new Webdriver;
  };

  exports.SPECIAL_KEYS = SPECIAL_KEYS;

}).call(this);
