// Generated by CoffeeScript 1.3.3
(function() {
  var SPECIAL_KEYS, Webdriver;

  Webdriver = require("./webdriver");

  SPECIAL_KEYS = require("./special-keys");

  exports.remote = function() {
    return new Webdriver;
  };

  exports.SPECIAL_KEYS = SPECIAL_KEYS;

}).call(this);
