// Generated by CoffeeScript 1.3.3
(function() {
  var test;

  test = require('../common-wd/basic-test-base').test;

  describe("wd-zombie", function() {
    return describe("unit", function() {
      return describe("basic test", function() {
        return describe("using chrome", function() {
          return test({}, {
            browserName: 'zombie'
          });
        });
      });
    });
  });

}).call(this);
