// Generated by CoffeeScript 1.3.3
(function() {
  var test;

  test = require('../common-wd/chain-test-base').test;

  describe("wd-zombie", function() {
    return describe("unit", function() {
      return describe("chain test", function() {
        return describe("using zombie", function() {
          return test('zombie');
        });
      });
    });
  });

}).call(this);
